# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 421a662fcf46ca6a8581452651061870545dbacb92a45e6c624ddf878aa8a38c557523b4cf511a5da37a54e1f1a3b3c535e7f9f83ff1d5221cc5e43a61c153dc

test:
  secret_key_base: 25ab17973cdec9eba148b07fe29e10d2f73907ca33703d4842960ae3b085ff0dd9ce30cbc79df48f6b510ce31f71a5c5bb41b3dedc47498431e80cb7a879d720

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
